fix: Makefile needs to use npm i, not npm ci
momentohq/signing-key-renewal-lambda pull request #8
Opened 2022-07-12 22:08 UTC by tylerburdsall

2022-07-12 22:10 UTC, bruuuuuuuce commented on Makefile
> +		&& npm i \
I think we want to use `npm ci`, and commit the `package-lock.json` here?

2022-07-12 22:11 UTC, tylerburdsall commented on Makefile
> +		&& npm i \
We can't commit a `package-lock.json` file that comes from Momento developers' systems, it commits our own NPM repos. This originally caused issues for a customer who had tried to use this before

2022-07-12 22:13 UTC, bruuuuuuuce commented on Makefile
> +		&& npm i \
ah gotchu

2022-07-12 22:14 UTC, bruuuuuuuce commented on Makefile
> +		&& npm i \
hmmm maybe we should just make it required that we only commit package-lock from public registry, like we are doing for cli

2022-07-12 22:14 UTC, bruuuuuuuce commented on Makefile
> +		&& npm i \
we can test it as part of ci.yaml, to make sure we can install all packages without needed to login to our own momento registry

2022-07-12 22:18 UTC, tylerburdsall commented on Makefile
> +		&& npm i \
That's the thing, there are no Momento registry packages in this repo. It's because of local NPM caching and configurations that will resolve through our own repos before the public NPM registry.

This behavior would be the same thing if someone working at FooBar Enterprises tried to commit their own package-lock.json, it would resolve first to their own registry

2022-07-12 22:19 UTC, tylerburdsall commented on Makefile
> +		&& npm i \
Perhaps sometime later I can pull this down on a personal machine and attempt to commit a package-lock.json file from there

2022-07-12 22:21 UTC, bruuuuuuuce commented on Makefile
> +		&& npm i \
Right, but we require that when commiting to our js sdk, that we don't allow our private registries to be committed. Basically you would need to run `rm -rf ~/.npmrc` first before doing an npm install. So we could in theory just do same thing here, which would allow us to pin our deps

2022-07-12 22:30 UTC, tylerburdsall commented on Makefile
> +		&& npm i \
Oh! That was the secret then, I was able to re-install and get it to work. Thanks for the suggestion!

2022-07-12 22:35 UTC, bruuuuuuuce requested changes
We should add a check in ci.yaml to make sure that we don't accidentally commit a package-lock that has the private momento registry in it, similar to how we do with the javascript sdk

2022-07-13 15:08 UTC, tylerburdsall commented
> We should add a check in ci.yaml to make sure that we don't accidentally commit a package-lock that has the private momento registry in it, similar to how we do with the javascript sdk

Ah, I see what you mean, yeah that is a great idea. I will commit that

2022-07-13 16:25 UTC, bruuuuuuuce commented on verify-package-lock.sh
> +private_repo=$(cat infrastructure/package-lock.json | { grep "momento-prod" || true; })
I _think_ this should work, but why not just run `npm ci` here, like we do in pipelines. Wouldn't that garuntee that we don't face this issue again? This is how its handled in the js sdk

2022-07-13 16:25 UTC, tylerburdsall commented on verify-package-lock.sh
> +private_repo=$(cat infrastructure/package-lock.json | { grep "momento-prod" || true; })
Oh gotcha, that makes sense! Yeah that's a lot simpler lol

2022-07-13 16:47 UTC, bruuuuuuuce approved these changes
:shipit:

2022-07-13 16:50 UTC, merged